package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"time"

	"github.com/muxi-ai/cli/pkg/context"
	"github.com/muxi-ai/cli/pkg/ui"
	"github.com/spf13/cobra"
)

// resolveFormationFilter returns the formation filter: explicit flag > auto-detect from formation dir
func resolveFormationFilter(cmd *cobra.Command) string {
	f, _ := cmd.Flags().GetString("formation")
	if f != "" {
		return f
	}
	if ctx, err := context.DetectFormation(); err == nil && ctx.ID != "" {
		return ctx.ID
	}
	return ""
}

var artifactsCmd = &cobra.Command{
	Use:   "artifacts",
	Short: "Manage saved artifacts",
	Long:  "List, open, and clean up file artifacts generated by formations.",
}

var artifactsListCmd = &cobra.Command{
	Use:   "list",
	Short: "List saved artifacts",
	RunE:  runArtifactsList,
}

var artifactsOpenCmd = &cobra.Command{
	Use:   "open",
	Short: "Open artifacts directory",
	RunE:  runArtifactsOpen,
}

var artifactsCleanupCmd = &cobra.Command{
	Use:   "cleanup",
	Short: "Remove old artifacts",
	RunE:  runArtifactsCleanup,
}

func init() {
	artifactsCleanupCmd.Flags().Int("days", 0, "Remove artifacts older than N days (0 = all)")
	artifactsCleanupCmd.Flags().String("formation", "", "Only clean artifacts for a specific formation")

	artifactsListCmd.Flags().String("formation", "", "Only list artifacts for a specific formation")

	rootCmd.AddCommand(artifactsCmd)
	artifactsCmd.AddCommand(artifactsListCmd)
	artifactsCmd.AddCommand(artifactsOpenCmd)
	artifactsCmd.AddCommand(artifactsCleanupCmd)
}

func getOutputsDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".muxi", "cli", "outputs"), nil
}

func runArtifactsList(cmd *cobra.Command, args []string) error {
	outputsDir, err := getOutputsDir()
	if err != nil {
		return err
	}

	formationFilter := resolveFormationFilter(cmd)

	if _, err := os.Stat(outputsDir); os.IsNotExist(err) {
		fmt.Println()
		ui.Dimmed("  No artifacts saved yet")
		return nil
	}

	formations, err := os.ReadDir(outputsDir)
	if err != nil {
		return fmt.Errorf("failed to read outputs directory: %w", err)
	}

	totalFiles := 0
	var totalSize int64

	fmt.Println()

	for _, f := range formations {
		if !f.IsDir() {
			continue
		}
		if formationFilter != "" && f.Name() != formationFilter {
			continue
		}

		formationDir := filepath.Join(outputsDir, f.Name())
		files, err := os.ReadDir(formationDir)
		if err != nil {
			continue
		}

		if len(files) == 0 {
			continue
		}

		fmt.Printf("  %s\n", ui.BoldText(f.Name()))

		// Sort by mod time (newest first)
		type fileEntry struct {
			name    string
			size    int64
			modTime time.Time
		}
		var entries []fileEntry
		for _, file := range files {
			if file.IsDir() {
				continue
			}
			info, err := file.Info()
			if err != nil {
				continue
			}
			entries = append(entries, fileEntry{
				name:    file.Name(),
				size:    info.Size(),
				modTime: info.ModTime(),
			})
		}
		sort.Slice(entries, func(i, j int) bool {
			return entries[i].modTime.After(entries[j].modTime)
		})

		for _, e := range entries {
			age := time.Since(e.modTime)
			ageStr := formatAge(age)
			fmt.Printf("    %s  %s  %s\n",
				e.name,
				ui.DimmedText(formatSize(e.size)),
				ui.DimmedText(ageStr),
			)
			totalFiles++
			totalSize += e.size
		}
		fmt.Println()
	}

	if totalFiles == 0 {
		ui.Dimmed("  No artifacts saved yet")
	} else {
		ui.Dimmed(fmt.Sprintf("  %d file(s), %s total", totalFiles, formatSize(totalSize)))
	}
	fmt.Println()

	return nil
}

func runArtifactsOpen(cmd *cobra.Command, args []string) error {
	outputsDir, err := getOutputsDir()
	if err != nil {
		return err
	}

	// Scope to formation if inside a formation dir
	if ctx, ctxErr := context.DetectFormation(); ctxErr == nil && ctx.ID != "" {
		outputsDir = filepath.Join(outputsDir, ctx.ID)
	}

	if err := os.MkdirAll(outputsDir, 0755); err != nil {
		return fmt.Errorf("failed to create outputs directory: %w", err)
	}

	var openCmd *exec.Cmd
	switch runtime.GOOS {
	case "darwin":
		openCmd = exec.Command("open", outputsDir)
	case "linux":
		openCmd = exec.Command("xdg-open", outputsDir)
	case "windows":
		openCmd = exec.Command("explorer", outputsDir)
	default:
		fmt.Println(outputsDir)
		return nil
	}

	if err := openCmd.Start(); err != nil {
		// Fallback: just print the path
		fmt.Println(outputsDir)
		return nil
	}

	fmt.Printf("  Opened %s\n", outputsDir)
	return nil
}

func runArtifactsCleanup(cmd *cobra.Command, args []string) error {
	outputsDir, err := getOutputsDir()
	if err != nil {
		return err
	}

	if _, err := os.Stat(outputsDir); os.IsNotExist(err) {
		ui.Dimmed("  No artifacts to clean up")
		return nil
	}

	days, _ := cmd.Flags().GetInt("days")
	formationFilter := resolveFormationFilter(cmd)

	var cutoff time.Time
	if days > 0 {
		cutoff = time.Now().Add(-time.Duration(days) * 24 * time.Hour)
	}

	removed := 0
	var freedBytes int64

	formations, err := os.ReadDir(outputsDir)
	if err != nil {
		return fmt.Errorf("failed to read outputs directory: %w", err)
	}

	for _, f := range formations {
		if !f.IsDir() {
			continue
		}
		if formationFilter != "" && f.Name() != formationFilter {
			continue
		}

		formationDir := filepath.Join(outputsDir, f.Name())

		if days == 0 {
			// Remove entire formation directory
			dirSize := getDirSize(formationDir)
			if err := os.RemoveAll(formationDir); err == nil {
				removed++
				freedBytes += dirSize
			}
			continue
		}

		// Remove files older than cutoff
		files, err := os.ReadDir(formationDir)
		if err != nil {
			continue
		}

		for _, file := range files {
			if file.IsDir() {
				continue
			}
			info, err := file.Info()
			if err != nil {
				continue
			}
			if info.ModTime().Before(cutoff) {
				path := filepath.Join(formationDir, file.Name())
				if err := os.Remove(path); err == nil {
					removed++
					freedBytes += info.Size()
				}
			}
		}

		// Remove formation dir if empty
		remaining, _ := os.ReadDir(formationDir)
		if len(remaining) == 0 {
			os.Remove(formationDir)
		}
	}

	fmt.Println()
	if removed == 0 {
		ui.Dimmed("  Nothing to clean up")
	} else {
		if days == 0 {
			ui.Success(fmt.Sprintf("Removed %d formation(s), freed %s", removed, formatSize(freedBytes)))
		} else {
			ui.Success(fmt.Sprintf("Removed %d file(s), freed %s", removed, formatSize(freedBytes)))
		}
	}
	fmt.Println()

	return nil
}

func getDirSize(path string) int64 {
	var size int64
	filepath.Walk(path, func(_ string, info os.FileInfo, err error) error {
		if err == nil && !info.IsDir() {
			size += info.Size()
		}
		return nil
	})
	return size
}

func formatSize(bytes int64) string {
	if bytes == 0 {
		return "0 B"
	}
	const unit = 1024
	if bytes < unit {
		return fmt.Sprintf("%d B", bytes)
	}
	div, exp := int64(unit), 0
	for n := bytes / unit; n >= unit; n /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %cB", float64(bytes)/float64(div), "KMGTPE"[exp])
}

func formatAge(d time.Duration) string {
	switch {
	case d < time.Minute:
		return "just now"
	case d < time.Hour:
		return fmt.Sprintf("%dm ago", int(d.Minutes()))
	case d < 24*time.Hour:
		return fmt.Sprintf("%dh ago", int(d.Hours()))
	default:
		days := int(d.Hours() / 24)
		if days == 1 {
			return "1 day ago"
		}
		return fmt.Sprintf("%d days ago", days)
	}
}
